dist: bionic

arch: amd64

language: go

go: tip

git:
  strategy: clone
  depth: 1
  quiet: true

notifications:
  email: gtheodorou035@gmail.com

if: branch = dev

before_script:
        - GO_FILES=$(find . -iname '*.go')
        - go get github.com/benhoyt/goawk
        - go get github.com/golang/lint/golint
        - go get honnef.co/go/tools/cmd/megacheck 
        - go get github.com/fzipp/gocyclo

script:
        - test -z $(gofmt -s -l $GO_FILES)
        - megacheck ./...
        - gocyclo -over 19 $GO_FILES
        - golint -set_exit_status $(go list ./...)

